# Generated by Django 5.0.6 on 2024-07-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_alter_cart_hari_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_hari',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
