# Generated by Django 5.0.6 on 2024-12-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_hari',
            name='sale_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
